import type { CmmsState } from "@/lib/types";
import { addDaysIso, todayIso } from "@/lib/utils";

const roleAdmin = "role_admin";
const roleManager = "role_manager";
const roleEngineer = "role_engineer";
const roleTechnician = "role_technician";
const clientId = "client_example";
const projectId = "project_example";
const siteId = "site_example";
const assetTypeId = "asset_type_life_safety";
const assetId = "asset_example";
const domainId = "domain_life_safety";
const activityTypeId = "activity_corrective";
const activityPmId = "activity_preventive";
const activityInstallId = "activity_installation";
const templateCmId = "template_corrective";
const templatePmId = "template_quarterly_pm";
const memberAdminId = "member_owner";
const memberEngineerId = "member_engineer";
const memberTechId = "member_technician";
const woCmId = "wo_corrective_seed";
const woPmId = "wo_pm_seed";

export const initialState: CmmsState = {
  company: {
    companyName: "SyncShield",
    companyType: "CMMS Operator",
    registrationNumber: "",
    taxNumber: "",
    address: "",
    phone: "",
    email: "",
    reportFooter: "Confidential maintenance record generated by SyncShield CMMS."
  },
  roles: [
    { id: roleAdmin, name: "CMMS Admin", description: "System owner and configuration administrator" },
    { id: roleManager, name: "Project Manager", description: "Owns work order planning and assignment" },
    { id: roleEngineer, name: "Engineer", description: "Completes assigned technical work and reports" },
    { id: roleTechnician, name: "Technician", description: "Executes field tasks and checklist items" }
  ],
  teamMembers: [
    {
      id: memberAdminId,
      employeeId: "EMP-2026-0001",
      fullName: "System Owner",
      roleId: roleAdmin,
      department: "Project Manager",
      phone: "",
      email: "owner@example.com",
      active: true
    },
    {
      id: memberEngineerId,
      employeeId: "EMP-2026-0002",
      fullName: "Field Engineer",
      roleId: roleEngineer,
      department: "Project Manager",
      phone: "",
      email: "engineer@example.com",
      active: true
    },
    {
      id: memberTechId,
      employeeId: "EMP-2026-0003",
      fullName: "Service Technician",
      roleId: roleTechnician,
      department: "Project Manager",
      phone: "",
      email: "technician@example.com",
      active: true
    }
  ],
  industries: ["Energy", "Healthcare", "Manufacturing", "Telecommunications", "Government"],
  clients: [
    {
      id: clientId,
      clientId: "CL-2026-0001",
      name: "Example Client",
      industry: "Energy",
      city: "City / Region",
      primaryContactName: "Primary Contact",
      primaryContactPhone: "",
      primaryContactEmail: "primary@example.com",
      secondaryContactName: "Secondary Contact",
      secondaryContactPhone: "",
      secondaryContactEmail: "secondary@example.com"
    }
  ],
  projects: [
    {
      id: projectId,
      name: "Example Maintenance Contract",
      clientId,
      contractNumber: "CONTRACT-001",
      startDate: todayIso(),
      endDate: addDaysIso(365),
      description: "Generic maintenance scope for demonstration data."
    }
  ],
  sites: [
    {
      id: siteId,
      name: "Example Facility",
      projectId,
      city: "City / Region",
      zone: "Zone / Area"
    }
  ],
  assetTypes: [{ id: assetTypeId, name: "Life Safety System" }],
  assets: [
    {
      id: assetId,
      assetName: "Example Asset",
      model: "Model",
      serialNumber: "SN-0001",
      description: "Equipment and Project Asset",
      manufacturer: "Manufacturer",
      assetTypeId,
      installationDate: "",
      warrantyPeriodYears: 2
    }
  ],
  domains: [{ id: domainId, name: "Life Safety Systems" }],
  activityTypes: [
    { id: activityTypeId, name: "Corrective Maintenance" },
    { id: activityPmId, name: "Preventive Maintenance" },
    { id: activityInstallId, name: "Installation" }
  ],
  taskCategories: ["Inspection", "Electrical", "Functional Test", "Documentation"],
  templates: [
    {
      id: templateCmId,
      domainId,
      name: "Corrective Response Template",
      activityTypeId,
      description: "Standard corrective maintenance checklist.",
      scope: "Inspect the reported issue, correct the fault, and document final status.",
      tasks: [
        { id: "task_cm_1", description: "Verify reported fault and isolate affected system.", category: "Inspection", required: true },
        { id: "task_cm_2", description: "Perform corrective action and record actual repair.", category: "Functional Test", required: true },
        { id: "task_cm_3", description: "Confirm system readiness with client representative.", category: "Documentation", required: false }
      ]
    },
    {
      id: templatePmId,
      domainId,
      name: "Quarterly Preventive Maintenance",
      activityTypeId,
      description: "Recurring preventive maintenance checklist.",
      scope: "Complete scheduled inspection, cleaning, testing, and report submission.",
      tasks: [
        { id: "task_pm_1", description: "Inspect asset condition and installation environment.", category: "Inspection", required: true },
        { id: "task_pm_2", description: "Run operational test and record readings.", category: "Functional Test", required: true },
        { id: "task_pm_3", description: "Update service labels and maintenance records.", category: "Documentation", required: false }
      ]
    }
  ],
  workOrders: [
    {
      id: woCmId,
      reference: "WO-2026-0001",
      kind: "CM",
      title: "Corrective maintenance visit",
      domainId,
      templateId: templateCmId,
      clientId,
      projectId,
      siteId,
      assetId,
      priority: "High",
      status: "In Progress",
      dueDate: addDaysIso(2),
      assignedMemberIds: [memberEngineerId, memberTechId],
      description: "Investigate and correct a reported field issue.",
      scope: "Inspect, repair, test, and submit corrective maintenance report.",
      tasks: [],
      createdAt: todayIso()
    },
    {
      id: woPmId,
      reference: "WO-2026-0002",
      kind: "PM",
      title: "Quarterly preventive maintenance",
      domainId,
      templateId: templatePmId,
      clientId,
      projectId,
      siteId,
      assetId,
      priority: "Medium",
      status: "Scheduled",
      dueDate: addDaysIso(12),
      assignedMemberIds: [memberEngineerId],
      description: "Scheduled quarterly PM.",
      scope: "Complete all preventive maintenance checklist tasks.",
      tasks: [],
      createdAt: todayIso()
    }
  ],
  reports: [],
  pmSchedules: [
    {
      id: "pm_seed_quarterly_asset",
      title: "Quarterly PM - Example Asset",
      projectId,
      assetId,
      frequency: "Quarterly",
      nextDueDate: addDaysIso(12),
      status: "Due",
      assignedMemberId: memberEngineerId,
      workOrderId: woPmId
    }
  ],
  pmScheduleSections: [
    {
      id: "pmsec_siren_head",
      title: "Siren Head & Mechanical",
      clientId,
      projectId,
      tasks: [
        { id: "pmtask_siren_visual", name: "Visual inspection of Siren Head for debris or nesting", frequency: "Monthly", assignedMemberId: memberEngineerId, assetId, cells: {} },
        { id: "pmtask_siren_activation", name: "Test siren activation via Gen 3 Controller", frequency: "Monthly", assignedMemberId: memberEngineerId, assetId, cells: {} },
        { id: "pmtask_siren_mounting", name: "Inspect mounting brackets and hanging hardware", frequency: "Quarterly", assignedMemberId: memberTechId, assetId, cells: {} }
      ]
    },
    {
      id: "pmsec_radio_controller",
      title: "Gen 3 Wireless Radio Controller",
      clientId,
      projectId,
      tasks: [
        { id: "pmtask_radio_power", name: "Check 220 VAC to 24 VDC Power Supply output voltage", frequency: "Quarterly", assignedMemberId: memberEngineerId, assetId, cells: {} },
        { id: "pmtask_radio_relays", name: "Inspect Omron LY2-D relays for carbon / wear", frequency: "Bi-Annual", assignedMemberId: memberTechId, assetId, cells: {} },
        { id: "pmtask_radio_signal", name: "Verify Maxon SD-171EX radio signal / reception", frequency: "Monthly", assignedMemberId: memberEngineerId, assetId, cells: {} }
      ]
    },
    {
      id: "pmsec_battery",
      title: "Battery & Charging Systems",
      clientId,
      projectId,
      tasks: [
        { id: "pmtask_battery_voltage", name: "Check 34R Battery terminal voltage", frequency: "Monthly", assignedMemberId: memberTechId, assetId, cells: {} },
        { id: "pmtask_battery_charger", name: "Inspect NOCO Pro charging system status LEDs", frequency: "Monthly", assignedMemberId: memberEngineerId, assetId, cells: {} },
        { id: "pmtask_battery_load", name: "Load-test batteries for siren runtime capacity", frequency: "Annual", assignedMemberId: memberEngineerId, assetId, cells: {} }
      ]
    }
  ],
  sequences: {
    employee: 3,
    client: 1,
    workOrder: 2,
    report: 0
  }
};

initialState.workOrders = initialState.workOrders.map((workOrder) => {
  const template = initialState.templates.find((item) => item.id === workOrder.templateId);
  return {
    ...workOrder,
    tasks: template ? template.tasks.map((task, index) => ({ ...task, id: `wo_task_${workOrder.id}_${index + 1}`, result: "Unchecked" })) : []
  };
});
